# Generated by Django 3.2.7 on 2021-10-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingoption',
            name='housing_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
