# Generated by Django 3.2.7 on 2021-10-25 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_housingoption_housing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingoption',
            name='housing_id',
        ),
    ]
