# Generated by Django 3.2.7 on 2021-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_housingoption_housing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingoption',
            name='website',
            field=models.CharField(default='x', max_length=1000),
            preserve_default=False,
        ),
    ]
