# Generated by Django 3.2.7 on 2021-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_housingoption_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingoption',
            name='website',
            field=models.CharField(max_length=3000),
        ),
    ]
