# Generated by Django 3.2.7 on 2021-11-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_housingoption_website'),
        ('housing', '0006_auto_20211102_1309'),
    ]

    operations = [
    ]
