# Generated by Django 3.2.7 on 2021-11-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_merge_20211105_1743'),
        ('housing', '0007_merge_20211105_1744'),
    ]

    operations = [
    ]
