# Generated by Django 3.2.7 on 2021-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingoption',
            name='photo',
            field=models.ImageField(default='https://i.stack.imgur.com/y9DpT.jpg', upload_to='images'),
        ),
    ]
