# Generated by Django 3.2.7 on 2021-11-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_auto_20211108_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
    ]
